# Generated by Django 5.2.15 on 2026-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0002_alter_designzone_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR provide a direct link to a product image', null=True),
        ),
    ]
