# Generated by Django 5.2.15 on 2026-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0003_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='OR provide a direct link to a product image', max_length=1000, null=True),
        ),
    ]
