# Generated by Django 5.2.15 on 2026-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0004_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='designzone',
            name='angle',
            field=models.FloatField(default=0.0),
        ),
    ]
