# Generated by Django 5.2.15 on 2026-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0005_designzone_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='designzone',
            name='side',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left', 'Left'), ('right', 'Right'), ('top', 'Top')], default='front', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Upload Back image file', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='back_image_url',
            field=models.CharField(blank=True, help_text='OR provide direct link to Back image', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='left_image',
            field=models.ImageField(blank=True, help_text='Upload Left image file', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='left_image_url',
            field=models.CharField(blank=True, help_text='OR provide direct link to Left image', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='right_image',
            field=models.ImageField(blank=True, help_text='Upload Right image file', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='right_image_url',
            field=models.CharField(blank=True, help_text='OR provide direct link to Right image', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shape_type',
            field=models.CharField(choices=[('cylinder', 'Cylinder (Bottle, Mug)'), ('box', 'Box (Notebook, Case)'), ('flat', 'Flat Surface (Cover, Tee)')], default='flat', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='top_image',
            field=models.ImageField(blank=True, help_text='Upload Top image file', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_image_url',
            field=models.CharField(blank=True, help_text='OR provide direct link to Top image', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload Front image file', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='OR provide direct link to Front image', max_length=1000, null=True),
        ),
    ]
