# Generated by Django 4.2.7 on 2026-06-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0006_designzone_side_product_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Upload 3D model (.gltf or .glb) file', null=True, upload_to='models/'),
        ),
    ]
