# Generated by Django 6.0.6 on 2026-07-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0008_client_product_client_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprintMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('visual_effect', models.CharField(choices=[('standard', 'Standard (Color Print)'), ('laser_engrave', 'Laser Engrave (Metallic Etch)'), ('deboss', 'Deboss / Emboss (Leather Stamp)'), ('full_color', 'Full Color Digital Print'), ('foil_stamp', 'Foil Stamp')], default='standard', max_length=30)),
                ('supports_color', models.BooleanField(default=True, help_text='If False (e.g. Laser Engrave), the color picker is hidden in the UI.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='available_imprint_methods',
            field=models.ManyToManyField(blank=True, help_text='Override: specific imprint methods available for this product. If empty, uses material defaults.', to='customizer.imprintmethod'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('compatible_methods', models.ManyToManyField(blank=True, help_text='Which imprint methods work on this material.', to='customizer.imprintmethod')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, help_text='The physical material of this product (used to auto-suggest imprint methods).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizer.material'),
        ),
    ]
