# Generated by Django 4.2.7 on 2026-07-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0009_imprintmethod_product_available_imprint_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designzone',
            name='side',
            field=models.CharField(default='front', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/views/')),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('fallback_3d_side', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left', 'Left'), ('right', 'Right'), ('top', 'Top')], default='front', help_text='Which side of the 3D shape should this view render on?', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='customizer.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
