# Generated by Django 4.2.7 on 2026-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0010_alter_designzone_side_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='designzone',
            name='name',
            field=models.CharField(blank=True, help_text="Optional custom name (e.g. 'Left Chest') to display as a view.", max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
