# Generated by Django 4.2.7 on 2026-07-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0011_designzone_name_delete_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='designzone',
            name='actual_height',
            field=models.FloatField(default=12.0, help_text='Max actual height in inches/cm'),
        ),
        migrations.AddField(
            model_name='designzone',
            name='actual_width',
            field=models.FloatField(default=12.0, help_text='Max actual width in inches/cm'),
        ),
    ]
