# Generated by Django 4.2.7 on 2026-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0012_designzone_actual_height_designzone_actual_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='designzone',
            name='source',
            field=models.CharField(default='2d', help_text='Whether zone was created in 2D or 3D', max_length=10),
        ),
    ]
