# Generated by Django 4.2.7 on 2026-08-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0013_designzone_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_product_id',
            field=models.CharField(blank=True, help_text='Marketplace or client product identifier.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_product_url',
            field=models.CharField(blank=True, help_text='Original storefront product URL (e.g. Nike.com link).', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tripo_job_id',
            field=models.CharField(blank=True, help_text='TripO generation job ID.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tripo_model_url',
            field=models.URLField(blank=True, help_text='URL to the generated TripO model.', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tripo_status',
            field=models.CharField(blank=True, help_text='TripO model generation status.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DesignSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('design_preview_url', models.TextField(blank=True, null=True)),
                ('pdf_spec_sheet_url', models.TextField(blank=True, null=True)),
                ('color_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('imprint_method', models.CharField(blank=True, max_length=100, null=True)),
                ('imprint_color', models.CharField(blank=True, max_length=100, null=True)),
                ('pms_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_submissions', to='customizer.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_submissions', to='customizer.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
