# Generated by Django 4.2.7 on 2026-08-06 10:00

import customizer.models
from django.db import migrations, models
import secrets

def populate_embed_token(apps, schema_editor):
    Product = apps.get_model('customizer', 'Product')
    for product in Product.objects.all():
        product.embed_token = secrets.token_urlsafe(32)
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0014_product_external_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embed_token',
            field=models.CharField(blank=True, default=customizer.models.generate_embed_token, help_text='Auto-generated URL-safe token. Use this in iframe URLs: ?embed_token=<value>. Never needs to be set manually.', max_length=64, null=True),
        ),
        migrations.RunPython(populate_embed_token, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='embed_token',
            field=models.CharField(blank=True, default=customizer.models.generate_embed_token, help_text='Auto-generated URL-safe token. Use this in iframe URLs: ?embed_token=<value>. Never needs to be set manually.', max_length=64, unique=True),
        ),
    ]
