# Generated by Django 4.2.7 on 2026-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0015_product_embed_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tripo_texture_quality',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('detailed', 'HD'), ('extreme', '8K')], help_text='Texture quality used for TripO 3D model generation.', max_length=20, null=True),
        ),
    ]
