# Generated by Django 4.2.7 on 2026-08-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0016_product_tripo_texture_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tripo_texture_quality',
        ),
        migrations.AddField(
            model_name='designzone',
            name='normal3d',
            field=models.JSONField(blank=True, help_text='[x,y,z] surface normal in 3D local space', null=True),
        ),
        migrations.AddField(
            model_name='designzone',
            name='point3d',
            field=models.JSONField(blank=True, help_text='[x,y,z] hit point in 3D local space', null=True),
        ),
        migrations.AddField(
            model_name='designzone',
            name='size3d',
            field=models.JSONField(blank=True, help_text='[w,h,d] decal bounds in 3D world space', null=True),
        ),
    ]
