# Generated by Django 4.2.7 on 2026-09-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0018_product_color_hex_product_color_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('back_image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('left_image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('right_image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('top_image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='customizer.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcolor',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_color_name'),
        ),
    ]
