# Generated by Django 4.2.7 on 2026-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0019_productcolor_productcolor_unique_product_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designzone',
            name='decoration_methods',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed decoration methods for this zone'),
        ),
    ]
